In [4]:
import numpy as np
from sympy import *

#prob 3.13
A1 = Matrix([[1,4,10],[0,2,0],[0,0,3]])
P1, J1 = A1.jordan_form()
print('A1: ', J1)

A2 = Matrix([[0,1,0],[0,0,1],[-2,-4,-3]])
P2, J2 = A2.jordan_form()
print('A2: ', J2)

A3 = Matrix([[1,0,-1], [0,1,0],[0,0,2]])
P3, J3 = A3.jordan_form()
print('A3: ', J3)

A4 = Matrix([[0,4,3],[0,20,16],[0,-25,-20]])
P4, J4 = A4.jordan_form()
print('A4: ', J4)

A1:  Matrix([[1, 0, 0], [0, 2, 0], [0, 0, 3]])
A2:  Matrix([[-1, 0, 0], [0, -1 - I, 0], [0, 0, -1 + I]])
A3:  Matrix([[1, 0, 0], [0, 1, 0], [0, 0, 2]])
A4:  Matrix([[0, 1, 0], [0, 0, 1], [0, 0, 0]])


In [5]:
# prob 3.14
a1 = symp.Symbol('a1')
a2 = symp.Symbol('a2')
a3 = symp.Symbol('a3')
a4 = symp.Symbol('a4')
l = symp.Symbol('l')
A = Matrix([[l+a1, a2, a3, a4], [-1, l, 0, 0], [0, -1, l, 0], [0, 0, -1, l]])
print(A)
print(A.det())

Matrix([[a1 + l, a2, a3, a4], [-1, l, 0, 0], [0, -1, l, 0], [0, 0, -1, l]])
a1*l**3 + a2*l**2 + a3*l + a4 + l**4


In [8]:
#prob 3.21
A21 = np.array([[1,1,0],[0,0,1],[0,0,1]])
print(np.linalg.matrix_power(A21, 2))
print('A21 pow: ', np.linalg.matrix_power(A21,103))

[[1 1 1]
 [0 0 1]
 [0 0 1]]
A21 pow:  [[  1   1 102]
 [  0   0   1]
 [  0   0   1]]
